name: Tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Composer dependencies
      run: composer install
    - name: Execute tests
      run: vendor/bin/phpunit